version: "0.1"

services:
  arrowhead-database:
    container_name: arrowhead-database
    image: aitiaiiot/arrowhead-database:4.6.1
    volumes:
      - arrowhead-database:/var/lib/mysql
    ports:
      - 3306:3306

  arrowhead-setup:
    container_name: arrowhead-setup
    build: 
      context: .
      dockerfile: ./setup/Dockerfile
    env_file:
      - .env
    depends_on:
      - arrowhead-database
    volumes:
      - ./:/setup

  arrowhead-serviceregistry:
    container_name: arrowhead-serviceregistry
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: serviceregistry
    env_file:
      - .env
    depends_on:
      arrowhead-setup:
        condition: service_completed_successfully
    volumes:
      - ./serviceregistry/application.properties:/opt/arrowhead/application.properties
      - ./serviceregistry/certificates:/opt/arrowhead/certificates
    ports:
      - 8443:8443
  
  arrowhead-authorization:
    container_name: arrowhead-authorization
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: authorization
    env_file:
      - .env
    depends_on:
      arrowhead-setup:
        condition: service_completed_successfully
    volumes:
      - ./authorization/application.properties:/opt/arrowhead/application.properties
      - ./authorization/certificates:/opt/arrowhead/certificates
    ports:
      - 8445:8445
      
  arrowhead-orchestrator:
    container_name: arrowhead-orchestrator
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: orchestrator
    env_file:
      - .env
    depends_on:
      arrowhead-setup:
        condition: service_completed_successfully
    volumes:
      - ./orchestrator/application.properties:/opt/arrowhead/application.properties
      - ./orchestrator/certificates:/opt/arrowhead/certificates
    ports:
      - 8441:8441

  arrowhead-gateway:
    container_name: arrowhead-gateway
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: gateway
    env_file:
      - .env
    depends_on:
      arrowhead-setup:
        condition: service_completed_successfully
    volumes:
      - ./gateway/application.properties:/opt/arrowhead/application.properties
      - ./gateway/certificates:/opt/arrowhead/certificates
    ports:
      - 8453:8453

  arrowhead-gatekeeper:
    container_name: arrowhead-gatekeeper
    image: aitiaiiot/arrowhead-system:4.6.1
    environment:
      SYSTEM_NAME: gatekeeper
    env_file:
      - .env
    depends_on:
      arrowhead-setup:
        condition: service_completed_successfully
    volumes:
      - ./gatekeeper/application.properties:/opt/arrowhead/application.properties
      - ./gatekeeper/certificates:/opt/arrowhead/certificates
    ports:
      - 8449:8449

volumes:
  arrowhead-database: